name: eeg
channels:
  - defaults
dependencies:
  - jupyterlab
  - python=3.9.4
  - pip=21.0.1
  - matplotlib
  - seaborn=0.11.1
<<<<<<< HEAD
=======
  - scipy=1.6.2
>>>>>>> 415a9a8... Updated README and added all files
  - fvcore
  - iopath
  - pip:
      - h5py==3.6.0
      - matplotlib==3.5.1
      - neptune_client==0.9.16
      - numpy==1.22.2
      - pandas==1.4.0
      - pytorch_lightning==1.3.5
      - scikit_learn==1.2.1
      - scipy==1.6.2
      - torch==1.10.2



